services:
    airflow:
        image: apache/airflow:latest
        ports:
        - "8080:8080"
        command: standalone
        volumes:
        - ./dags:/opt/airflow/dags
        - ./pysrc:/opt/airflow/pysrc
        environment:
        - PYTHONPATH=/opt/airflow/pysrc

    
    minio:
        image: minio/minio:RELEASE.2025-04-03T14-56-28Z
        ports:
        - "9000:9000"
        - "9001:9001"
        environment:
        - MINIO_ROOT_USER=minioadmin
        - MINIO_ROOT_PASSWORD=minioadmin
        command: server /data --console-address ":9001"
        volumes:
        - ./minio_data:/data

    